server: 
  port: 22223
spring:
  application:
    name: config-test1-dev
  profiles:
    active: dev
  cloud:
    zookeeper:
      connect-string: 192.168.1.146:2184
    config:
      discovery:
        enabled: true
        service-id: config-test1-dev
